swagger: "2.0"
info:
  version: "1.0.0"
  title: "Poll API"
  description: "API for managing Polls and Options"
paths:
  /telegram-updates:
    post:
      summary: "Receive updates from Telegram"
      operationId: "ReceiveTelegramUpdates"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
      responses:
        default:
          description: "A standard response, details will be handled in the application code."
  /polls:
    post:
      summary: "Create a new Poll"
      operationId: "CreatePoll"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Poll object to be created"
          required: true
          schema:
            $ref: "#/definitions/CreatePoll"
      responses:
        201:
          description: "Poll created successfully"
          schema:
            $ref: "#/definitions/Poll"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
  /polls/{pollId}:
    get:
      summary: "Get a Poll by its ID"
      operationId: "GetPollByID"
      produces:
        - application/json
      parameters:
        - in: "path"
          name: "pollId"
          required: true
          type: "integer"
          format: "int32"
      responses:
        200:
          description: "Poll found successfully"
          schema:
            $ref: "#/definitions/Poll"
        404:
          description: "Poll not found"
        500:
          description: "Internal server error"
    put:
      summary: "Update an existing Poll"
      operationId: "UpdatePoll"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "path"
          name: "pollId"
          required: true
          type: "integer"
          format: "int32"
        - in: "body"
          name: "body"
          description: "Updated Poll object"
          required: true
          schema:
            $ref: "#/definitions/Poll"
      responses:
        200:
          description: "Poll updated successfully"
          schema:
            $ref: "#/definitions/Poll"
        400:
          description: "Bad request"
        404:
          description: "Poll not found"
        500:
          description: "Internal server error"
    delete:
      summary: "Delete a Poll by its ID"
      operationId: "DeletePoll"
      parameters:
        - in: "path"
          name: "pollId"
          required: true
          type: "integer"
          format: "int32"
      responses:
        204:
          description: "Poll deleted successfully"
        404:
          description: "Poll not found"
        500:
          description: "Internal server error"
  /options:
    post:
      summary: "Create a new Option"
      operationId: "CreateOption"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Option object to be created"
          required: true
          schema:
            $ref: "#/definitions/CreateOption"
      responses:
        201:
          description: "Option created successfully"
          schema:
            $ref: "#/definitions/Option"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
  /options/{optionId}:
    put:
      summary: "Update an existing Option"
      operationId: "UpdateOption"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "path"
          name: "optionId"
          required: true
          type: "integer"
          format: "int32"
        - in: "body"
          name: "body"
          description: "Updated Option object"
          required: true
          schema:
            $ref: "#/definitions/Option"
      responses:
        200:
          description: "Option updated successfully"
          schema:
            $ref: "#/definitions/Option"
        400:
          description: "Bad request"
        404:
          description: "Option not found"
        500:
          description: "Internal server error"
    delete:
      summary: "Delete an Option by its ID"
      operationId: "DeleteOption"
      parameters:
        - in: "path"
          name: "optionId"
          required: true
          type: "integer"
          format: "int32"
      responses:
        204:
          description: "Option deleted successfully"
        404:
          description: "Option not found"
        500:
          description: "Internal server error"
definitions:
  CreatePoll:
    type: "object"
    properties:
      Title:
        type: "string"
      Description:
        type: "string"
      Start:
        type: "string"
        format: "date-time"
      Finish:
        type: "string"
        format: "date-time"
  Poll:
    type: "object"
    properties:
      ID:
        type: "integer"
        format: "int32"
      Title:
        type: "string"
      Description:
        type: "string"
      Start:
        type: "string"
        format: "date-time"
      Finish:
        type: "string"
        format: "date-time"
      CreatedAt:
        type: "string"
        format: "date-time"
      UpdatedAt:
        type: "string"
        format: "date-time"
  CreateOption:
    type: "object"
    properties:
      PollID:
        type: "integer"
        format: "int32"
      Title:
        type: "string"
      Description:
        type: "string"
  Option:
    type: "object"
    properties:
      ID:
        type: "integer"
        format: "int32"
      PollID:
        type: "integer"
        format: "int32"
      Title:
        type: "string"
      Description:
        type: "string"
