// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.6.1
// source: internal/core/forecaster/telegram/proto/deletepoll/deletepollpreview.proto

package deletepoll

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeletePoll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PollId              *int32 `protobuf:"varint,1,req,name=poll_id,json=pollId" json:"poll_id,omitempty"`
	ReferrerMyPollsPage *int32 `protobuf:"varint,2,opt,name=referrer_my_polls_page,json=referrerMyPollsPage" json:"referrer_my_polls_page,omitempty"`
	NeedConfirmation    *bool  `protobuf:"varint,3,opt,name=need_confirmation,json=needConfirmation" json:"need_confirmation,omitempty"`
}

func (x *DeletePoll) Reset() {
	*x = DeletePoll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoll) ProtoMessage() {}

func (x *DeletePoll) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoll.ProtoReflect.Descriptor instead.
func (*DeletePoll) Descriptor() ([]byte, []int) {
	return file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescGZIP(), []int{0}
}

func (x *DeletePoll) GetPollId() int32 {
	if x != nil && x.PollId != nil {
		return *x.PollId
	}
	return 0
}

func (x *DeletePoll) GetReferrerMyPollsPage() int32 {
	if x != nil && x.ReferrerMyPollsPage != nil {
		return *x.ReferrerMyPollsPage
	}
	return 0
}

func (x *DeletePoll) GetNeedConfirmation() bool {
	if x != nil && x.NeedConfirmation != nil {
		return *x.NeedConfirmation
	}
	return false
}

var File_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto protoreflect.FileDescriptor

var file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDesc = []byte{
	0x0a, 0x4a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x66, 0x6f, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x70, 0x6f, 0x6c, 0x6c, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x70, 0x6f, 0x6c, 0x6c, 0x70,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x70, 0x6f, 0x6c, 0x6c, 0x22, 0x87, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x6c, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x6c, 0x49, 0x64,
	0x12, 0x33, 0x0a, 0x16, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x5f, 0x6d, 0x79, 0x5f,
	0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x13, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x4d, 0x79, 0x50, 0x6f, 0x6c, 0x6c,
	0x73, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x10, 0x6e, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x70, 0x6f,
	0x6c, 0x6c,
}

var (
	file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescOnce sync.Once
	file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescData = file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDesc
)

func file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescGZIP() []byte {
	file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescOnce.Do(func() {
		file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescData)
	})
	return file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDescData
}

var file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_goTypes = []interface{}{
	(*DeletePoll)(nil), // 0: deletepoll.DeletePoll
}
var file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_init() }
func file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_init() {
	if File_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePoll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_goTypes,
		DependencyIndexes: file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_depIdxs,
		MessageInfos:      file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_msgTypes,
	}.Build()
	File_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto = out.File
	file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_rawDesc = nil
	file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_goTypes = nil
	file_internal_core_forecaster_telegram_proto_deletepoll_deletepollpreview_proto_depIdxs = nil
}
