// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Poll API
//
//	This is a sample server for a poll management API.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
