// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSeries create series
//
// swagger:model CreateSeries
type CreateSeries struct {

	// description
	Description string `json:"Description,omitempty"`

	// title
	Title string `json:"Title,omitempty"`
}

// Validate validates this create series
func (m *CreateSeries) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create series based on context it is used
func (m *CreateSeries) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSeries) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSeries) UnmarshalBinary(b []byte) error {
	var res CreateSeries
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
