// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateOption create option
//
// swagger:model CreateOption
type CreateOption struct {

	// description
	Description string `json:"Description,omitempty"`

	// poll ID
	PollID int32 `json:"PollID,omitempty"`

	// title
	Title string `json:"Title,omitempty"`
}

// Validate validates this create option
func (m *CreateOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create option based on context it is used
func (m *CreateOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateOption) UnmarshalBinary(b []byte) error {
	var res CreateOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
