// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateSeries update series
//
// swagger:model UpdateSeries
type UpdateSeries struct {

	// description
	Description string `json:"Description,omitempty"`

	// ID
	ID int32 `json:"ID,omitempty"`

	// title
	Title string `json:"Title,omitempty"`
}

// Validate validates this update series
func (m *UpdateSeries) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update series based on context it is used
func (m *UpdateSeries) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateSeries) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateSeries) UnmarshalBinary(b []byte) error {
	var res UpdateSeries
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
