// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// CreateSeriesCreatedCode is the HTTP code returned for type CreateSeriesCreated
const CreateSeriesCreatedCode int = 201

/*
CreateSeriesCreated Series created successfully

swagger:response createSeriesCreated
*/
type CreateSeriesCreated struct {

	/*
	  In: Body
	*/
	Payload *swagger.Series `json:"body,omitempty"`
}

// NewCreateSeriesCreated creates CreateSeriesCreated with default headers values
func NewCreateSeriesCreated() *CreateSeriesCreated {

	return &CreateSeriesCreated{}
}

// WithPayload adds the payload to the create series created response
func (o *CreateSeriesCreated) WithPayload(payload *swagger.Series) *CreateSeriesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create series created response
func (o *CreateSeriesCreated) SetPayload(payload *swagger.Series) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSeriesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSeriesBadRequestCode is the HTTP code returned for type CreateSeriesBadRequest
const CreateSeriesBadRequestCode int = 400

/*
CreateSeriesBadRequest Bad request

swagger:response createSeriesBadRequest
*/
type CreateSeriesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewCreateSeriesBadRequest creates CreateSeriesBadRequest with default headers values
func NewCreateSeriesBadRequest() *CreateSeriesBadRequest {

	return &CreateSeriesBadRequest{}
}

// WithPayload adds the payload to the create series bad request response
func (o *CreateSeriesBadRequest) WithPayload(payload *swagger.Error) *CreateSeriesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create series bad request response
func (o *CreateSeriesBadRequest) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSeriesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSeriesInternalServerErrorCode is the HTTP code returned for type CreateSeriesInternalServerError
const CreateSeriesInternalServerErrorCode int = 500

/*
CreateSeriesInternalServerError Internal server error

swagger:response createSeriesInternalServerError
*/
type CreateSeriesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewCreateSeriesInternalServerError creates CreateSeriesInternalServerError with default headers values
func NewCreateSeriesInternalServerError() *CreateSeriesInternalServerError {

	return &CreateSeriesInternalServerError{}
}

// WithPayload adds the payload to the create series internal server error response
func (o *CreateSeriesInternalServerError) WithPayload(payload *swagger.Error) *CreateSeriesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create series internal server error response
func (o *CreateSeriesInternalServerError) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSeriesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateSeriesDefault error

swagger:response createSeriesDefault
*/
type CreateSeriesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewCreateSeriesDefault creates CreateSeriesDefault with default headers values
func NewCreateSeriesDefault(code int) *CreateSeriesDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateSeriesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create series default response
func (o *CreateSeriesDefault) WithStatusCode(code int) *CreateSeriesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create series default response
func (o *CreateSeriesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create series default response
func (o *CreateSeriesDefault) WithPayload(payload *swagger.Error) *CreateSeriesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create series default response
func (o *CreateSeriesDefault) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSeriesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
