// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateSeriesHandlerFunc turns a function with the right signature into a create series handler
type CreateSeriesHandlerFunc func(CreateSeriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSeriesHandlerFunc) Handle(params CreateSeriesParams) middleware.Responder {
	return fn(params)
}

// CreateSeriesHandler interface for that can handle valid create series params
type CreateSeriesHandler interface {
	Handle(CreateSeriesParams) middleware.Responder
}

// NewCreateSeries creates a new http.Handler for the create series operation
func NewCreateSeries(ctx *middleware.Context, handler CreateSeriesHandler) *CreateSeries {
	return &CreateSeries{Context: ctx, Handler: handler}
}

/*
CreateSeries swagger:route POST /series createSeries

Create a new Series
*/
type CreateSeries struct {
	Context *middleware.Context
	Handler CreateSeriesHandler
}

func (o *CreateSeries) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateSeriesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
