// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// CreatePollCreatedCode is the HTTP code returned for type CreatePollCreated
const CreatePollCreatedCode int = 201

/*
CreatePollCreated Poll created successfully

swagger:response createPollCreated
*/
type CreatePollCreated struct {

	/*
	  In: Body
	*/
	Payload *swagger.Poll `json:"body,omitempty"`
}

// NewCreatePollCreated creates CreatePollCreated with default headers values
func NewCreatePollCreated() *CreatePollCreated {

	return &CreatePollCreated{}
}

// WithPayload adds the payload to the create poll created response
func (o *CreatePollCreated) WithPayload(payload *swagger.Poll) *CreatePollCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create poll created response
func (o *CreatePollCreated) SetPayload(payload *swagger.Poll) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePollCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePollBadRequestCode is the HTTP code returned for type CreatePollBadRequest
const CreatePollBadRequestCode int = 400

/*
CreatePollBadRequest Bad request

swagger:response createPollBadRequest
*/
type CreatePollBadRequest struct {
}

// NewCreatePollBadRequest creates CreatePollBadRequest with default headers values
func NewCreatePollBadRequest() *CreatePollBadRequest {

	return &CreatePollBadRequest{}
}

// WriteResponse to the client
func (o *CreatePollBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreatePollInternalServerErrorCode is the HTTP code returned for type CreatePollInternalServerError
const CreatePollInternalServerErrorCode int = 500

/*
CreatePollInternalServerError Internal server error

swagger:response createPollInternalServerError
*/
type CreatePollInternalServerError struct {
}

// NewCreatePollInternalServerError creates CreatePollInternalServerError with default headers values
func NewCreatePollInternalServerError() *CreatePollInternalServerError {

	return &CreatePollInternalServerError{}
}

// WriteResponse to the client
func (o *CreatePollInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
