// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// CreatePollCreatedCode is the HTTP code returned for type CreatePollCreated
const CreatePollCreatedCode int = 201

/*
CreatePollCreated Poll created successfully

swagger:response createPollCreated
*/
type CreatePollCreated struct {

	/*
	  In: Body
	*/
	Payload *swagger.Poll `json:"body,omitempty"`
}

// NewCreatePollCreated creates CreatePollCreated with default headers values
func NewCreatePollCreated() *CreatePollCreated {

	return &CreatePollCreated{}
}

// WithPayload adds the payload to the create poll created response
func (o *CreatePollCreated) WithPayload(payload *swagger.Poll) *CreatePollCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create poll created response
func (o *CreatePollCreated) SetPayload(payload *swagger.Poll) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePollCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePollBadRequestCode is the HTTP code returned for type CreatePollBadRequest
const CreatePollBadRequestCode int = 400

/*
CreatePollBadRequest Bad request

swagger:response createPollBadRequest
*/
type CreatePollBadRequest struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewCreatePollBadRequest creates CreatePollBadRequest with default headers values
func NewCreatePollBadRequest() *CreatePollBadRequest {

	return &CreatePollBadRequest{}
}

// WithPayload adds the payload to the create poll bad request response
func (o *CreatePollBadRequest) WithPayload(payload *swagger.Error) *CreatePollBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create poll bad request response
func (o *CreatePollBadRequest) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePollBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePollInternalServerErrorCode is the HTTP code returned for type CreatePollInternalServerError
const CreatePollInternalServerErrorCode int = 500

/*
CreatePollInternalServerError Internal server error

swagger:response createPollInternalServerError
*/
type CreatePollInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewCreatePollInternalServerError creates CreatePollInternalServerError with default headers values
func NewCreatePollInternalServerError() *CreatePollInternalServerError {

	return &CreatePollInternalServerError{}
}

// WithPayload adds the payload to the create poll internal server error response
func (o *CreatePollInternalServerError) WithPayload(payload *swagger.Error) *CreatePollInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create poll internal server error response
func (o *CreatePollInternalServerError) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePollInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreatePollDefault error

swagger:response createPollDefault
*/
type CreatePollDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewCreatePollDefault creates CreatePollDefault with default headers values
func NewCreatePollDefault(code int) *CreatePollDefault {
	if code <= 0 {
		code = 500
	}

	return &CreatePollDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create poll default response
func (o *CreatePollDefault) WithStatusCode(code int) *CreatePollDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create poll default response
func (o *CreatePollDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create poll default response
func (o *CreatePollDefault) WithPayload(payload *swagger.Error) *CreatePollDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create poll default response
func (o *CreatePollDefault) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePollDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
