// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// CreateOptionCreatedCode is the HTTP code returned for type CreateOptionCreated
const CreateOptionCreatedCode int = 201

/*
CreateOptionCreated Option created successfully

swagger:response createOptionCreated
*/
type CreateOptionCreated struct {

	/*
	  In: Body
	*/
	Payload *swagger.Option `json:"body,omitempty"`
}

// NewCreateOptionCreated creates CreateOptionCreated with default headers values
func NewCreateOptionCreated() *CreateOptionCreated {

	return &CreateOptionCreated{}
}

// WithPayload adds the payload to the create option created response
func (o *CreateOptionCreated) WithPayload(payload *swagger.Option) *CreateOptionCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create option created response
func (o *CreateOptionCreated) SetPayload(payload *swagger.Option) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOptionCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateOptionBadRequestCode is the HTTP code returned for type CreateOptionBadRequest
const CreateOptionBadRequestCode int = 400

/*
CreateOptionBadRequest Bad request

swagger:response createOptionBadRequest
*/
type CreateOptionBadRequest struct {
}

// NewCreateOptionBadRequest creates CreateOptionBadRequest with default headers values
func NewCreateOptionBadRequest() *CreateOptionBadRequest {

	return &CreateOptionBadRequest{}
}

// WriteResponse to the client
func (o *CreateOptionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateOptionInternalServerErrorCode is the HTTP code returned for type CreateOptionInternalServerError
const CreateOptionInternalServerErrorCode int = 500

/*
CreateOptionInternalServerError Internal server error

swagger:response createOptionInternalServerError
*/
type CreateOptionInternalServerError struct {
}

// NewCreateOptionInternalServerError creates CreateOptionInternalServerError with default headers values
func NewCreateOptionInternalServerError() *CreateOptionInternalServerError {

	return &CreateOptionInternalServerError{}
}

// WriteResponse to the client
func (o *CreateOptionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
