// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteSeriesParams creates a new DeleteSeriesParams object
// no default values defined in spec.
func NewDeleteSeriesParams() DeleteSeriesParams {

	return DeleteSeriesParams{}
}

// DeleteSeriesParams contains all the bound params for the delete series operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteSeries
type DeleteSeriesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	SeriesID int32
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteSeriesParams() beforehand.
func (o *DeleteSeriesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSeriesID, rhkSeriesID, _ := route.Params.GetOK("seriesId")
	if err := o.bindSeriesID(rSeriesID, rhkSeriesID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSeriesID binds and validates parameter SeriesID from path.
func (o *DeleteSeriesParams) bindSeriesID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("seriesId", "path", "int32", raw)
	}
	o.SeriesID = value

	return nil
}
