// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteOptionNoContentCode is the HTTP code returned for type DeleteOptionNoContent
const DeleteOptionNoContentCode int = 204

/*
DeleteOptionNoContent Option deleted successfully

swagger:response deleteOptionNoContent
*/
type DeleteOptionNoContent struct {
}

// NewDeleteOptionNoContent creates DeleteOptionNoContent with default headers values
func NewDeleteOptionNoContent() *DeleteOptionNoContent {

	return &DeleteOptionNoContent{}
}

// WriteResponse to the client
func (o *DeleteOptionNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteOptionNotFoundCode is the HTTP code returned for type DeleteOptionNotFound
const DeleteOptionNotFoundCode int = 404

/*
DeleteOptionNotFound Option not found

swagger:response deleteOptionNotFound
*/
type DeleteOptionNotFound struct {
}

// NewDeleteOptionNotFound creates DeleteOptionNotFound with default headers values
func NewDeleteOptionNotFound() *DeleteOptionNotFound {

	return &DeleteOptionNotFound{}
}

// WriteResponse to the client
func (o *DeleteOptionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteOptionInternalServerErrorCode is the HTTP code returned for type DeleteOptionInternalServerError
const DeleteOptionInternalServerErrorCode int = 500

/*
DeleteOptionInternalServerError Internal server error

swagger:response deleteOptionInternalServerError
*/
type DeleteOptionInternalServerError struct {
}

// NewDeleteOptionInternalServerError creates DeleteOptionInternalServerError with default headers values
func NewDeleteOptionInternalServerError() *DeleteOptionInternalServerError {

	return &DeleteOptionInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteOptionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
