// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteOptionHandlerFunc turns a function with the right signature into a delete option handler
type DeleteOptionHandlerFunc func(DeleteOptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteOptionHandlerFunc) Handle(params DeleteOptionParams) middleware.Responder {
	return fn(params)
}

// DeleteOptionHandler interface for that can handle valid delete option params
type DeleteOptionHandler interface {
	Handle(DeleteOptionParams) middleware.Responder
}

// NewDeleteOption creates a new http.Handler for the delete option operation
func NewDeleteOption(ctx *middleware.Context, handler DeleteOptionHandler) *DeleteOption {
	return &DeleteOption{Context: ctx, Handler: handler}
}

/*
	DeleteOption swagger:route DELETE /options/{optionId} deleteOption

Delete an Option by its ID
*/
type DeleteOption struct {
	Context *middleware.Context
	Handler DeleteOptionHandler
}

func (o *DeleteOption) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteOptionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
