// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePollNoContentCode is the HTTP code returned for type DeletePollNoContent
const DeletePollNoContentCode int = 204

/*
DeletePollNoContent Poll deleted successfully

swagger:response deletePollNoContent
*/
type DeletePollNoContent struct {
}

// NewDeletePollNoContent creates DeletePollNoContent with default headers values
func NewDeletePollNoContent() *DeletePollNoContent {

	return &DeletePollNoContent{}
}

// WriteResponse to the client
func (o *DeletePollNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeletePollNotFoundCode is the HTTP code returned for type DeletePollNotFound
const DeletePollNotFoundCode int = 404

/*
DeletePollNotFound Poll not found

swagger:response deletePollNotFound
*/
type DeletePollNotFound struct {
}

// NewDeletePollNotFound creates DeletePollNotFound with default headers values
func NewDeletePollNotFound() *DeletePollNotFound {

	return &DeletePollNotFound{}
}

// WriteResponse to the client
func (o *DeletePollNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeletePollInternalServerErrorCode is the HTTP code returned for type DeletePollInternalServerError
const DeletePollInternalServerErrorCode int = 500

/*
DeletePollInternalServerError Internal server error

swagger:response deletePollInternalServerError
*/
type DeletePollInternalServerError struct {
}

// NewDeletePollInternalServerError creates DeletePollInternalServerError with default headers values
func NewDeletePollInternalServerError() *DeletePollInternalServerError {

	return &DeletePollInternalServerError{}
}

// WriteResponse to the client
func (o *DeletePollInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
