// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// DeleteSeriesNoContentCode is the HTTP code returned for type DeleteSeriesNoContent
const DeleteSeriesNoContentCode int = 204

/*
DeleteSeriesNoContent Series deleted successfully

swagger:response deleteSeriesNoContent
*/
type DeleteSeriesNoContent struct {
}

// NewDeleteSeriesNoContent creates DeleteSeriesNoContent with default headers values
func NewDeleteSeriesNoContent() *DeleteSeriesNoContent {

	return &DeleteSeriesNoContent{}
}

// WriteResponse to the client
func (o *DeleteSeriesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteSeriesNotFoundCode is the HTTP code returned for type DeleteSeriesNotFound
const DeleteSeriesNotFoundCode int = 404

/*
DeleteSeriesNotFound Series not found

swagger:response deleteSeriesNotFound
*/
type DeleteSeriesNotFound struct {
}

// NewDeleteSeriesNotFound creates DeleteSeriesNotFound with default headers values
func NewDeleteSeriesNotFound() *DeleteSeriesNotFound {

	return &DeleteSeriesNotFound{}
}

// WriteResponse to the client
func (o *DeleteSeriesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteSeriesInternalServerErrorCode is the HTTP code returned for type DeleteSeriesInternalServerError
const DeleteSeriesInternalServerErrorCode int = 500

/*
DeleteSeriesInternalServerError Internal server error

swagger:response deleteSeriesInternalServerError
*/
type DeleteSeriesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewDeleteSeriesInternalServerError creates DeleteSeriesInternalServerError with default headers values
func NewDeleteSeriesInternalServerError() *DeleteSeriesInternalServerError {

	return &DeleteSeriesInternalServerError{}
}

// WithPayload adds the payload to the delete series internal server error response
func (o *DeleteSeriesInternalServerError) WithPayload(payload *swagger.Error) *DeleteSeriesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete series internal server error response
func (o *DeleteSeriesInternalServerError) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSeriesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DeleteSeriesDefault error

swagger:response deleteSeriesDefault
*/
type DeleteSeriesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewDeleteSeriesDefault creates DeleteSeriesDefault with default headers values
func NewDeleteSeriesDefault(code int) *DeleteSeriesDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteSeriesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete series default response
func (o *DeleteSeriesDefault) WithStatusCode(code int) *DeleteSeriesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete series default response
func (o *DeleteSeriesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete series default response
func (o *DeleteSeriesDefault) WithPayload(payload *swagger.Error) *DeleteSeriesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete series default response
func (o *DeleteSeriesDefault) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSeriesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
