// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSeriesHandlerFunc turns a function with the right signature into a delete series handler
type DeleteSeriesHandlerFunc func(DeleteSeriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSeriesHandlerFunc) Handle(params DeleteSeriesParams) middleware.Responder {
	return fn(params)
}

// DeleteSeriesHandler interface for that can handle valid delete series params
type DeleteSeriesHandler interface {
	Handle(DeleteSeriesParams) middleware.Responder
}

// NewDeleteSeries creates a new http.Handler for the delete series operation
func NewDeleteSeries(ctx *middleware.Context, handler DeleteSeriesHandler) *DeleteSeries {
	return &DeleteSeries{Context: ctx, Handler: handler}
}

/*
DeleteSeries swagger:route DELETE /series/{seriesId} deleteSeries

Delete a Series by its ID
*/
type DeleteSeries struct {
	Context *middleware.Context
	Handler DeleteSeriesHandler
}

func (o *DeleteSeries) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteSeriesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
