// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// GetPollByIDOKCode is the HTTP code returned for type GetPollByIDOK
const GetPollByIDOKCode int = 200

/*
GetPollByIDOK Poll found successfully

swagger:response getPollByIdOK
*/
type GetPollByIDOK struct {

	/*
	  In: Body
	*/
	Payload *swagger.Poll `json:"body,omitempty"`
}

// NewGetPollByIDOK creates GetPollByIDOK with default headers values
func NewGetPollByIDOK() *GetPollByIDOK {

	return &GetPollByIDOK{}
}

// WithPayload adds the payload to the get poll by Id o k response
func (o *GetPollByIDOK) WithPayload(payload *swagger.Poll) *GetPollByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get poll by Id o k response
func (o *GetPollByIDOK) SetPayload(payload *swagger.Poll) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPollByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPollByIDNotFoundCode is the HTTP code returned for type GetPollByIDNotFound
const GetPollByIDNotFoundCode int = 404

/*
GetPollByIDNotFound Poll not found

swagger:response getPollByIdNotFound
*/
type GetPollByIDNotFound struct {
}

// NewGetPollByIDNotFound creates GetPollByIDNotFound with default headers values
func NewGetPollByIDNotFound() *GetPollByIDNotFound {

	return &GetPollByIDNotFound{}
}

// WriteResponse to the client
func (o *GetPollByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetPollByIDInternalServerErrorCode is the HTTP code returned for type GetPollByIDInternalServerError
const GetPollByIDInternalServerErrorCode int = 500

/*
GetPollByIDInternalServerError Internal server error

swagger:response getPollByIdInternalServerError
*/
type GetPollByIDInternalServerError struct {
}

// NewGetPollByIDInternalServerError creates GetPollByIDInternalServerError with default headers values
func NewGetPollByIDInternalServerError() *GetPollByIDInternalServerError {

	return &GetPollByIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetPollByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
