// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewReceiveTelegramUpdatesParams creates a new ReceiveTelegramUpdatesParams object
//
// There are no default values defined in the spec.
func NewReceiveTelegramUpdatesParams() ReceiveTelegramUpdatesParams {

	return ReceiveTelegramUpdatesParams{}
}

// ReceiveTelegramUpdatesParams contains all the bound params for the receive telegram updates operation
// typically these are obtained from a http.Request
//
// swagger:parameters ReceiveTelegramUpdates
type ReceiveTelegramUpdatesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Body io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewReceiveTelegramUpdatesParams() beforehand.
func (o *ReceiveTelegramUpdatesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		o.Body = r.Body
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
