// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*
ReceiveTelegramUpdatesDefault A standard response, details will be handled in the application code.

swagger:response receiveTelegramUpdatesDefault
*/
type ReceiveTelegramUpdatesDefault struct {
	_statusCode int
}

// NewReceiveTelegramUpdatesDefault creates ReceiveTelegramUpdatesDefault with default headers values
func NewReceiveTelegramUpdatesDefault(code int) *ReceiveTelegramUpdatesDefault {
	if code <= 0 {
		code = 500
	}

	return &ReceiveTelegramUpdatesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the receive telegram updates default response
func (o *ReceiveTelegramUpdatesDefault) WithStatusCode(code int) *ReceiveTelegramUpdatesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the receive telegram updates default response
func (o *ReceiveTelegramUpdatesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *ReceiveTelegramUpdatesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
