// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// UpdateOptionOKCode is the HTTP code returned for type UpdateOptionOK
const UpdateOptionOKCode int = 200

/*
UpdateOptionOK Option updated successfully

swagger:response updateOptionOK
*/
type UpdateOptionOK struct {

	/*
	  In: Body
	*/
	Payload *swagger.Option `json:"body,omitempty"`
}

// NewUpdateOptionOK creates UpdateOptionOK with default headers values
func NewUpdateOptionOK() *UpdateOptionOK {

	return &UpdateOptionOK{}
}

// WithPayload adds the payload to the update option o k response
func (o *UpdateOptionOK) WithPayload(payload *swagger.Option) *UpdateOptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update option o k response
func (o *UpdateOptionOK) SetPayload(payload *swagger.Option) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOptionBadRequestCode is the HTTP code returned for type UpdateOptionBadRequest
const UpdateOptionBadRequestCode int = 400

/*
UpdateOptionBadRequest Bad request

swagger:response updateOptionBadRequest
*/
type UpdateOptionBadRequest struct {
}

// NewUpdateOptionBadRequest creates UpdateOptionBadRequest with default headers values
func NewUpdateOptionBadRequest() *UpdateOptionBadRequest {

	return &UpdateOptionBadRequest{}
}

// WriteResponse to the client
func (o *UpdateOptionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateOptionNotFoundCode is the HTTP code returned for type UpdateOptionNotFound
const UpdateOptionNotFoundCode int = 404

/*
UpdateOptionNotFound Option not found

swagger:response updateOptionNotFound
*/
type UpdateOptionNotFound struct {
}

// NewUpdateOptionNotFound creates UpdateOptionNotFound with default headers values
func NewUpdateOptionNotFound() *UpdateOptionNotFound {

	return &UpdateOptionNotFound{}
}

// WriteResponse to the client
func (o *UpdateOptionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateOptionInternalServerErrorCode is the HTTP code returned for type UpdateOptionInternalServerError
const UpdateOptionInternalServerErrorCode int = 500

/*
UpdateOptionInternalServerError Internal server error

swagger:response updateOptionInternalServerError
*/
type UpdateOptionInternalServerError struct {
}

// NewUpdateOptionInternalServerError creates UpdateOptionInternalServerError with default headers values
func NewUpdateOptionInternalServerError() *UpdateOptionInternalServerError {

	return &UpdateOptionInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateOptionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
