// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// UpdateSeriesOKCode is the HTTP code returned for type UpdateSeriesOK
const UpdateSeriesOKCode int = 200

/*
UpdateSeriesOK Series updated successfully

swagger:response updateSeriesOK
*/
type UpdateSeriesOK struct {

	/*
	  In: Body
	*/
	Payload *swagger.Series `json:"body,omitempty"`
}

// NewUpdateSeriesOK creates UpdateSeriesOK with default headers values
func NewUpdateSeriesOK() *UpdateSeriesOK {

	return &UpdateSeriesOK{}
}

// WithPayload adds the payload to the update series o k response
func (o *UpdateSeriesOK) WithPayload(payload *swagger.Series) *UpdateSeriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update series o k response
func (o *UpdateSeriesOK) SetPayload(payload *swagger.Series) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSeriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSeriesBadRequestCode is the HTTP code returned for type UpdateSeriesBadRequest
const UpdateSeriesBadRequestCode int = 400

/*
UpdateSeriesBadRequest Bad request

swagger:response updateSeriesBadRequest
*/
type UpdateSeriesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewUpdateSeriesBadRequest creates UpdateSeriesBadRequest with default headers values
func NewUpdateSeriesBadRequest() *UpdateSeriesBadRequest {

	return &UpdateSeriesBadRequest{}
}

// WithPayload adds the payload to the update series bad request response
func (o *UpdateSeriesBadRequest) WithPayload(payload *swagger.Error) *UpdateSeriesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update series bad request response
func (o *UpdateSeriesBadRequest) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSeriesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSeriesNotFoundCode is the HTTP code returned for type UpdateSeriesNotFound
const UpdateSeriesNotFoundCode int = 404

/*
UpdateSeriesNotFound Series not found

swagger:response updateSeriesNotFound
*/
type UpdateSeriesNotFound struct {
}

// NewUpdateSeriesNotFound creates UpdateSeriesNotFound with default headers values
func NewUpdateSeriesNotFound() *UpdateSeriesNotFound {

	return &UpdateSeriesNotFound{}
}

// WriteResponse to the client
func (o *UpdateSeriesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateSeriesInternalServerErrorCode is the HTTP code returned for type UpdateSeriesInternalServerError
const UpdateSeriesInternalServerErrorCode int = 500

/*
UpdateSeriesInternalServerError Internal server error

swagger:response updateSeriesInternalServerError
*/
type UpdateSeriesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewUpdateSeriesInternalServerError creates UpdateSeriesInternalServerError with default headers values
func NewUpdateSeriesInternalServerError() *UpdateSeriesInternalServerError {

	return &UpdateSeriesInternalServerError{}
}

// WithPayload adds the payload to the update series internal server error response
func (o *UpdateSeriesInternalServerError) WithPayload(payload *swagger.Error) *UpdateSeriesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update series internal server error response
func (o *UpdateSeriesInternalServerError) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSeriesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
UpdateSeriesDefault error

swagger:response updateSeriesDefault
*/
type UpdateSeriesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewUpdateSeriesDefault creates UpdateSeriesDefault with default headers values
func NewUpdateSeriesDefault(code int) *UpdateSeriesDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateSeriesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update series default response
func (o *UpdateSeriesDefault) WithStatusCode(code int) *UpdateSeriesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update series default response
func (o *UpdateSeriesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update series default response
func (o *UpdateSeriesDefault) WithPayload(payload *swagger.Error) *UpdateSeriesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update series default response
func (o *UpdateSeriesDefault) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSeriesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
