// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// NewUpdateOptionParams creates a new UpdateOptionParams object
//
// There are no default values defined in the spec.
func NewUpdateOptionParams() UpdateOptionParams {

	return UpdateOptionParams{}
}

// UpdateOptionParams contains all the bound params for the update option operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateOption
type UpdateOptionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Updated Option object
	  Required: true
	  In: body
	*/
	Option *swagger.UpdateOption
	/*
	  Required: true
	  In: path
	*/
	OptionID int16
	/*
	  Required: true
	  In: path
	*/
	PollID int32
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateOptionParams() beforehand.
func (o *UpdateOptionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body swagger.UpdateOption
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("option", "body", ""))
			} else {
				res = append(res, errors.NewParseError("option", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Option = &body
			}
		}
	} else {
		res = append(res, errors.Required("option", "body", ""))
	}

	rOptionID, rhkOptionID, _ := route.Params.GetOK("optionId")
	if err := o.bindOptionID(rOptionID, rhkOptionID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPollID, rhkPollID, _ := route.Params.GetOK("pollId")
	if err := o.bindPollID(rPollID, rhkPollID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindOptionID binds and validates parameter OptionID from path.
func (o *UpdateOptionParams) bindOptionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt16(raw)
	if err != nil {
		return errors.InvalidType("optionId", "path", "int16", raw)
	}
	o.OptionID = value

	return nil
}

// bindPollID binds and validates parameter PollID from path.
func (o *UpdateOptionParams) bindPollID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("pollId", "path", "int32", raw)
	}
	o.PollID = value

	return nil
}
