// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/babadro/forecaster/internal/models/swagger"
)

// NewUpdateSeriesParams creates a new UpdateSeriesParams object
//
// There are no default values defined in the spec.
func NewUpdateSeriesParams() UpdateSeriesParams {

	return UpdateSeriesParams{}
}

// UpdateSeriesParams contains all the bound params for the update series operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateSeries
type UpdateSeriesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Updated Series object
	  Required: true
	  In: body
	*/
	Series *swagger.Series
	/*
	  Required: true
	  In: path
	*/
	SeriesID int32
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateSeriesParams() beforehand.
func (o *UpdateSeriesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body swagger.Series
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("series", "body", ""))
			} else {
				res = append(res, errors.NewParseError("series", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Series = &body
			}
		}
	} else {
		res = append(res, errors.Required("series", "body", ""))
	}

	rSeriesID, rhkSeriesID, _ := route.Params.GetOK("seriesId")
	if err := o.bindSeriesID(rSeriesID, rhkSeriesID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSeriesID binds and validates parameter SeriesID from path.
func (o *UpdateSeriesParams) bindSeriesID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("seriesId", "path", "int32", raw)
	}
	o.SeriesID = value

	return nil
}
