// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdatePollHandlerFunc turns a function with the right signature into a update poll handler
type UpdatePollHandlerFunc func(UpdatePollParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdatePollHandlerFunc) Handle(params UpdatePollParams) middleware.Responder {
	return fn(params)
}

// UpdatePollHandler interface for that can handle valid update poll params
type UpdatePollHandler interface {
	Handle(UpdatePollParams) middleware.Responder
}

// NewUpdatePoll creates a new http.Handler for the update poll operation
func NewUpdatePoll(ctx *middleware.Context, handler UpdatePollHandler) *UpdatePoll {
	return &UpdatePoll{Context: ctx, Handler: handler}
}

/*UpdatePoll swagger:route PUT /polls/{pollId} updatePoll

Update an existing Poll

*/
type UpdatePoll struct {
	Context *middleware.Context
	Handler UpdatePollHandler
}

func (o *UpdatePoll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdatePollParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
