// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePollBadRequestCode is the HTTP code returned for type DeletePollBadRequest
const DeletePollBadRequestCode int = 400

/*
DeletePollBadRequest Invalid ID supplied

swagger:response deletePollBadRequest
*/
type DeletePollBadRequest struct {
}

// NewDeletePollBadRequest creates DeletePollBadRequest with default headers values
func NewDeletePollBadRequest() *DeletePollBadRequest {

	return &DeletePollBadRequest{}
}

// WriteResponse to the client
func (o *DeletePollBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeletePollNotFoundCode is the HTTP code returned for type DeletePollNotFound
const DeletePollNotFoundCode int = 404

/*
DeletePollNotFound Poll not found

swagger:response deletePollNotFound
*/
type DeletePollNotFound struct {
}

// NewDeletePollNotFound creates DeletePollNotFound with default headers values
func NewDeletePollNotFound() *DeletePollNotFound {

	return &DeletePollNotFound{}
}

// WriteResponse to the client
func (o *DeletePollNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
