// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePollOKCode is the HTTP code returned for type UpdatePollOK
const UpdatePollOKCode int = 200

/*
UpdatePollOK Poll updated

swagger:response updatePollOK
*/
type UpdatePollOK struct {
}

// NewUpdatePollOK creates UpdatePollOK with default headers values
func NewUpdatePollOK() *UpdatePollOK {

	return &UpdatePollOK{}
}

// WriteResponse to the client
func (o *UpdatePollOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdatePollBadRequestCode is the HTTP code returned for type UpdatePollBadRequest
const UpdatePollBadRequestCode int = 400

/*
UpdatePollBadRequest Invalid input

swagger:response updatePollBadRequest
*/
type UpdatePollBadRequest struct {
}

// NewUpdatePollBadRequest creates UpdatePollBadRequest with default headers values
func NewUpdatePollBadRequest() *UpdatePollBadRequest {

	return &UpdatePollBadRequest{}
}

// WriteResponse to the client
func (o *UpdatePollBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdatePollNotFoundCode is the HTTP code returned for type UpdatePollNotFound
const UpdatePollNotFoundCode int = 404

/*
UpdatePollNotFound Poll not found

swagger:response updatePollNotFound
*/
type UpdatePollNotFound struct {
}

// NewUpdatePollNotFound creates UpdatePollNotFound with default headers values
func NewUpdatePollNotFound() *UpdatePollNotFound {

	return &UpdatePollNotFound{}
}

// WriteResponse to the client
func (o *UpdatePollNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
