swagger: "2.0"
info:
  description: "This is a sample server for a poll management API."
  version: "1.0.0"
  title: "Poll API"
paths:
  /polls:
    post:
      summary: "Create poll"
      operationId: "createPoll"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Poll object that needs to be added."
          required: true
          schema:
            $ref: "#/definitions/Poll"
      responses:
        "201":
          description: "Poll created"
        "400":
          description: "Invalid input"
  /polls/{pollId}:
    get:
      summary: "Get poll by ID"
      operationId: "getPollById"
      produces:
        - "application/json"
      parameters:
        - name: "pollId"
          in: "path"
          description: "ID of poll to return"
          required: true
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Poll"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Poll not found"
    put:
      summary: "Update an existing poll"
      operationId: "updatePoll"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "pollId"
          description: "ID of poll that needs to be updated"
          required: true
          type: "integer"
          format: "int32"
        - in: "body"
          name: "body"
          description: "Updated poll object"
          required: true
          schema:
            $ref: "#/definitions/Poll"
      responses:
        "200":
          description: "Poll updated"
        "400":
          description: "Invalid input"
        "404":
          description: "Poll not found"
    delete:
      summary: "Deletes a poll"
      operationId: "deletePoll"
      produces:
        - "application/json"
      parameters:
        - name: "pollId"
          in: "path"
          description: "Poll id to delete"
          required: true
          type: "integer"
          format: "int32"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Poll not found"
definitions:
  Poll:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      title:
        type: "string"
      description:
        type: "string"
      start:
        type: "string"
        format: "date-time"
      finish:
        type: "string"
        format: "date-time"
    xml:
      name: "Poll"
